In [2]:
import numpy as np

In [3]:
arr1=np.array([[1,2,3],[2,4,5],[4,7,8]])
arr1

array([[1, 2, 3],
       [2, 4, 5],
       [4, 7, 8]])

In [4]:
zeros_arr=np.zeros(5,dtype="int")
zeros_arr
zeros_arr.dtype



dtype('int64')

In [5]:
a=np.array([[1,2,3,4],[4,5,6,7],[6,8,4,9],])
a.dtype

a

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [6, 8, 4, 9]])

In [6]:
a.dtype

dtype('int64')

In [7]:
a.shape

(3, 4)

In [8]:
a.ndim

2

In [9]:
c=np.array([[1,2,3],[5,7,9]])
b=np.swapaxes(c,0,1)
b

array([[1, 5],
       [2, 7],
       [3, 9]])

In [10]:
c.max()

np.int64(9)

In [11]:
a.reshape(2,6)


array([[1, 2, 3, 4, 4, 5],
       [6, 7, 6, 8, 4, 9]])

In [15]:
arr = np.linspace(1, 6, 12)
arr
arr_2d = arr.reshape(3, 4)
arr_2d

array([[1.        , 1.45454545, 1.90909091, 2.36363636],
       [2.81818182, 3.27272727, 3.72727273, 4.18181818],
       [4.63636364, 5.09090909, 5.54545455, 6.        ]])

In [16]:
import numpy as np

arr = np.array([
    [3, 1],
    [2, 4]
])

print("Original array:")
print(arr)


Original array:
[[3 1]
 [2 4]]


In [17]:
sorted_axis0 = np.sort(arr, axis=0)
print("\nSorted along axis=0 (by columns):")
print(sorted_axis0)



Sorted along axis=0 (by columns):
[[2 1]
 [3 4]]


In [18]:
sorted_axis1 = np.sort(arr, axis=1)
print("\nSorted along axis=1 (by rows):")
print(sorted_axis1)



Sorted along axis=1 (by rows):
[[1 3]
 [2 4]]
